### PR TITLE
Add hassfest action docker requirements

### LINKED ISSUE #7: Hassfest is failing with the latest 0.115.0b0 beta release
This is happening on my custom_component repo and on the template [custom_component/blueprint](https://github.com/custom-components/blueprint) repo too.

https://github.com/custom-components/blueprint/runs/1083586935?check_suite_focus=true#step:6:12

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 7, in <module>
    from . import (
  File "/usr/src/homeassistant/script/hassfest/requirements.py", line 8, in <module>
    from stdlib_list import stdlib_list
ModuleNotFoundError: No module named 'stdlib_list'
```

### PR DESCRIPTION
**Pull request by MartinHjelmare**
- Add needed action Python requirements to the hassfest docker file.

fixes #7

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
I haven't tested this yet.

**Comment by MartinHjelmare** [comment]
Not working yet.

**Comment by MartinHjelmare** [comment]
I've now tested building the docker file locally and it installs the requirements from PyPI. Can you run the image locally easily?

**Comment by ludeeus** [comment]
```
cd hassfest
docker build . -t hassfest
docker run --rm --name hassfest -v PATH_TO_INTEGRATIONS:/github/workspace hassfest
```

**Comment by MartinHjelmare** [comment]
Thanks! I managed to run the image now. Note that the volume mount seems to need the homeassistant directory and not the components directory.
```
x:~/Dev/home-assistant/actions/hassfest$ docker run --rm --name hassfest -v /home/martin/Dev/home-assistant/home-assistant/homeassistant/:/github/workspace hassfest
Validating json... done in 0.81s
Validating codeowners... done in 0.00s
Validating config_flow... done in 0.03s
Validating dependencies... done in 11.67s
Validating manifest... done in 0.07s
Validating services... done in 1.55s
Validating ssdp... done in 0.00s
Validating translations... done in 1.71s
Validating zeroconf... done in 0.00s

Integrations: 956
Invalid integrations: 4

Integration dsmr - components/dsmr:
* [TRANSLATIONS] Invalid translations/en.json: required key not provided @ data['config']['step']. Got None

Integration ebusd - components/ebusd:
* [TRANSLATIONS] Invalid translations/en.json: expected dictionary for dictionary value @ data['state']['day']. Got 'Day'
expected dictionary for dictionary value @ data['state']['night']. Got 'Night'

Integration firmata - components/firmata:
* [TRANSLATIONS] Invalid translations/en.json: required key not provided @ data['config']['step']. Got None

Integration rfxtrx - components/rfxtrx:
* [TRANSLATIONS] Invalid translations/en.json: required key not provided @ data['config']['step']. Got None

Integration season - components/season:
* [WARNING] [TRANSLATIONS] Invalid sensor.en.json: invalid device class season__season__. After domain__, needs to be all lowercase, no spaces. for dictionary value @ data['state']. Got {'season__season': {'autumn': 'Autumn', 'spring': 'Spring', 'summer': 'Summer', 'winter': 'Winter'}, 'season__season__': {'autumn': 'Autumn', 'spring': 'Spring', 'summer': 'Summer', 'winter': 'Winter'}}

Integration zone - components/zone:
* [WARNING] [TRANSLATIONS] config.title key has been moved out of config and into the root of strings.json. Starting Home Assistant 0.109 you only need to define this key in the root if the title needs to be different than the name of your integration in the manifest.
```

**Comment by ludeeus** [comment]
Hmm. the "components" dir should have worked :thinking: 
But that does not matter, looking good :+1:

**Comment by MartinHjelmare** [comment]
Got this when trying the components dir:
```
x:~/Dev/home-assistant/actions/hassfest$ docker run --rm --name hassfest -v /home/martin/Dev/home-assistant/home-assistant/homeassistant/components/:/github/workspace hassfest
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/github/workspace/script/__init__.py", line 8, in <module>
    from homeassistant.const import (
  File "/github/workspace/homeassistant/__init__.py", line 8, in <module>
    from homeassistant.auth.permissions.const import CAT_ENTITIES, POLICY_CONTROL
ModuleNotFoundError: No module named 'homeassistant.auth'
```

**Review by ludeeus — APPROVED** [review]

**Pull request merged**
