### PR TITLE
Use environment variables for generated and passed inputs

### PR DESCRIPTION
**Pull request by ludeeus**

### CODE REVIEW

**Comment by agners** [comment]
The [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) mentions only variables in the github context. But inputs could be passed from one of those in the context as well, so I think it is sensible to also make sure inputs are only passed through environment variables to scripts.

Maybe @pwntester can comment on this?

**Review by agners — APPROVED** [review]

**Comment by pwntester** [comment]
I would leave that to the experts /cc @jarlob @jorgectf

**Comment by jorgectf** [comment]
> The [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) mentions only variables in the github context. But inputs could be passed from one of those in the context as well, so I think it is sensible to also make sure inputs are only passed through environment variables to scripts.

Great point. This is a bit of an edge case because most guiding focus on workflows that are not meant to be reused (and so not use inputs), but every value that can be attacker-controlled (such as github context, workflow inputs) should be first "encapsulated" in environment variables.

**Review by balloob — APPROVED** [review]

**Comment by jorgectf** [comment]
> So yeah, I have to say that the recommendation [Using an action instead of an inline script (recommended)](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-action-instead-of-an-inline-script-recommended) feel a bit incomplete to me. The recommendation says:
> 
> > The recommended approach is to create an action that processes the context value as an argument.
> 
> So the assumption is that the reader has to implement `fakeaction/checktitle@v3`. But it leaves the implementation of that action up to the reader... Maybe the guidelines should at least mention that the same care must be taken for inputs in that actions implementation?
> 
> When I've read this recommendation I was actually wondering if the inputs are somehow sanitized by GitHub Actions. because one can interpret the recommendation as merely passing to another action solves the problem. However, in fact passing the same (attacker controlled) context through an input just delegates the responsibility to the action instead.

Thank you for your comments! I agree that the [Using an intermediate environment variable](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable) section should not only target inline scripts (`For inline scripts`), but all kind of contexts instead.

cc @jarlob

**Pull request merged**
